version: '3'
services:
    app:
        container_name: sgcoop-app
        build: .
        command: npm run dev:run
        ports:
            # - 3000:3000
            - 8000:8000
        env_file: 
            - ./.docker/.env
        volumes:
            - .:/src/
            - nodemodules:/src/node_modules
        links:
            - postgresdb
        depends_on: 
            - postgresdb
    postgresdb:
        container_name: sgcoop-postgresdb
        image: postgres
        volumes:
            - ./../data/postgres:/data/postgres
            - ./.docker/postgres/:/docker-entrypoint-initdb.d/
        ports:
           - "5432:5432"
        expose: 
            - 5432
        env_file: 
            - ./.docker/.env
    pgadmin:
        container_name: sgcoop-pgadmin
        image: dpage/pgadmin4
        env_file: 
            - ./.docker/.env
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
volumes:
    nodemodules: {}
    pgadmin: {}