version: '3'
services:
    # mongodb:
    #     image: mongo:4
    #     ports:
    #         - 27017:27017
    app:
        build: .
        command: npm run dev:run
        ports:
            - 3000:3000
            - 8000:8000
        environment: 
            # MONGO_URL: mongodb
            PORT: 8000
        volumes:
            - .:/src/
            - nodemodules:/src/node_modules
        # links:
        #     - mongodb
        # depends_on: 
        #     - mongodb
    postgresdb:
        image: postgres
        volumes:
            - ./../data/postgres:/data/postgres
        ports:
           - "5432:5432"
        expose: 
            - 5432
        # environment:
        #     POSTGRES_PASSWORD: ${POSTGRES_SQL_PASSWORD}
        env_file: 
            - ./.env

volumes:
    nodemodules: {}
    # postgres: {}